module.exports = {
  lastname : 'VARCHAR(70) / mandatory',
  firstname : 'VARCHAR(30) / mandatory',
  maiden_name : 'VARCHAR(70) / optional',
  email : 'VARCHAR(80) / optional or mandatory',
  technical_id : 'VARCHAR(50) / mandatory',
  registration_references: 'LIST',
  dob : 'YYYY-MM-DD / optional',
  address1 : 'VARCHAR(255) / optional or mandatory',
  address2 : 'VARCHAR(255) / optional',
  address3 : 'VARCHAR(255) / optional',
  zip_code : 'VARCHAR(30) / optional or mandatory',
  city : 'VARCHAR(100) / optional or mandatory',
  country : 'VARCHAR(2) / optional or mandatory',
  phone_number : 'VARCHAR(50) / optional',
  mobile_phone_number : 'VARCHAR(50) / optional',
  disable_elec_distribution : 'true/false / optional',
  disable_paper_distribution : 'true/false / optional',
  starting_date: 'YYYY-MM-DD / optional',
  gone : 'true/false / optional',
  disable_vault : 'true/false / optional',
  filters: 'optional'
};