module.exports = {
  lastname : 'VARCHAR(70) / mandatory',
  firstname : 'VARCHAR(30) / mandatory',
  maiden_name : 'VARCHAR(70)',
  email : 'VARCHAR(80)',
  technical_id : 'VARCHAR(50) / mandatory',
  registration_references: [require('./registrationReference')],
  dob : 'YYYY-MM-DD',
  address1 : 'VARCHAR(255)',
  address2 : 'VARCHAR(255)',
  address3 : 'VARCHAR(255)',
  zip_code : 'VARCHAR(30)',
  city : 'VARCHAR(100)',
  country : 'VARCHAR(2)',
  phone_number : 'VARCHAR(50)',
  mobile_phone_number : 'VARCHAR(50)',
  disable_elec_distribution : 'BOOLEAN',
  disable_paper_distribution : 'BOOLEAN',
  starting_date: 'YYYY-MM-DD',
  gone : 'BOOLEAN',
  disable_vault : 'BOOLEAN',
  filters: '*'
};